<a href="https://colab.research.google.com/github/EmadSoheili/DeepLearning-UofT-NeuralNetworksCanvas/blob/main/Standardization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import our dependencies

import pandas as pd
from sklearn.preprocessing import StandardScaler

In [4]:
# Load data

hr_df = pd.read_csv('hr_dataset.csv')
hr_df.head()

   Satisfaction_Level  Num_Projects  Time_Spent  Num_Promotions
0                0.30             1         253               2
1                0.25             1         200               0
2                0.90             4        2880               5
3                0.65             3        1450               3
4                0.50             2         785               2

In [5]:
# Standardize

scaler = StandardScaler()
scaler.fit(hr_df)
scaled_data = scaler.transform(hr_df)

# Create scaled dataframe

transformed_scaled_data = pd.DataFrame(scaled_data, columns=hr_df.columns)
transformed_scaled_data.head()

   Satisfaction_Level  Num_Projects  Time_Spent  Num_Promotions
0           -1.303615     -1.162476   -1.049481       -0.558656
1           -1.512945     -1.162476   -1.094603       -1.804887
2            1.208335      0.860233    1.187080        1.310692
3            0.161689      0.185996   -0.030385        0.064460
4           -0.466299     -0.488240   -0.596549       -0.558656